// Generated by CoffeeScript 1.4.0
var addParamsToPath, http, querystring, url;

http = require("http");

url = require("url");

querystring = require("querystring");

addParamsToPath = function(options) {
  var pathUrl, _ref;
  pathUrl = url.parse(options.path || "", true);
  if ((_ref = options.params) == null) {
    options.params = {};
  }
  options.params.f = "json";
  pathUrl.query = options.params;
  return options.path = url.format(pathUrl);
};

module.exports = {
  serializeBody: function(body) {
    var key, result, stringifiedBody;
    result = "";
    for (key in body) {
      if (typeof body[key] === "object") {
        stringifiedBody = JSON.stringify(body[key]);
      } else {
        stringifiedBody = body[key].toString();
      }
      result += "&" + key + "=" + stringifiedBody;
    }
    return result.substring(1);
  },
  get: function(options, callback) {
    var req;
    if (options == null) {
      options = {};
    }
    if (options.host == null) {
      throw new Error("Must include host in options");
    }
    addParamsToPath(options);
    req = http.request(options);
    req.on("response", function(res) {
      var result;
      result = "";
      res.on("data", function(data) {
        return result += data;
      });
      return res.on("end", function() {
        var resultAsJson;
        resultAsJson = null;
        try {
          resultAsJson = JSON.parse(result);
        } catch (err) {
          resultAsJson = {
            error: "Response body is not valid JSON",
            responseBody: result
          };
        }
        if (callback) {
          return callback(resultAsJson);
        }
      });
    });
    return req.end();
  },
  post: function(options, callback) {
    var body, req;
    if (options == null) {
      options = {};
    }
    if (options.host == null) {
      throw new Error("Must include host in options");
    }
    options.path || (options.path = "");
    options.method = "POST";
    options.headers = {
      "Content-Type": "application/x-www-form-urlencoded"
    };
    if (options.params) {
      options.params.f = "json";
    }
    body = this.serializeBody(options.params);
    req = http.request(options);
    req.on("response", function(res) {
      var result;
      result = "";
      res.on("data", function(data) {
        return result += data;
      });
      return res.on("end", function() {
        var resultAsJson;
        resultAsJson = null;
        try {
          resultAsJson = JSON.parse(result);
        } catch (err) {
          resultAsJson = {
            error: "Response body is not valid JSON",
            responseBody: result
          };
        }
        if (callback) {
          return callback(resultAsJson);
        }
      });
    });
    return req.end(body);
  }
};
